export const seededMonsterFeed = {
  items: [
    {
      id: "orange-mushroom",
      name: "Orange Mushroom",
      image: null,
      portrait: "OM",
      type: "Normal",
      category: "Mushroom",
      level: 8,
      hp: 80,
      strength: 8,
      difficulty: 10,
      difficultyLabel: "Low",
      description: "The classic Victoria Island mushroom. Easy to clear and familiar to every MapleStory player.",
      shortDescription: "Starter route classic.",
      weaknesses: ["Low mobility", "Vulnerable to burst"],
      drops: [{ name: "Mushroom Cap", rarity: "Common", kind: "Material" }],
      locations: [{ region: "Victoria Island", map: "Mushroom Garden", area: "Field lanes" }],
      isBoss: false,
      isElite: false,
      farmingScore: 22,
      farmingTier: "Low",
      farmingTags: ["Starter route"],
      farmingReason: "Fast clears for early quests."
    },
    {
      id: "slime",
      name: "Slime",
      image: null,
      portrait: "SL",
      type: "Normal",
      category: "Slime",
      level: 12,
      hp: 180,
      strength: 10,
      difficulty: 14,
      difficultyLabel: "Low",
      description: "A smooth low-level farming target thanks to density and easy movement patterns.",
      shortDescription: "Dense and easy to clear.",
      weaknesses: ["Low defense", "Weak to clean burst"],
      drops: [{ name: "Slime Bubble", rarity: "Common", kind: "Material" }],
      locations: [{ region: "Victoria Island", map: "The Forest East of Henesys", area: "Flat clear route" }],
      isBoss: false,
      isElite: false,
      farmingScore: 33,
      farmingTier: "Solid",
      farmingTags: ["Easy farm"],
      farmingReason: "Good density and forgiving map flow."
    },
    {
      id: "dual-ghost-pirate",
      name: "Dual Ghost Pirate",
      image: null,
      portrait: "DG",
      type: "Elite",
      category: "Machine",
      level: 74,
      hp: 55000,
      strength: 70,
      difficulty: 66,
      difficultyLabel: "High",
      description: "A compact Ludibrium grind target known for efficient mobbing routes.",
      shortDescription: "Famous efficient grind target.",
      weaknesses: ["Holy Weak", "Burst windows"],
      drops: [{ name: "Broken Machine Part", rarity: "Common", kind: "Material" }],
      locations: [{ region: "Ludibrium", map: "Ghost Ship 2", area: "Tight platform loop" }],
      isBoss: false,
      isElite: true,
      farmingScore: 76,
      farmingTier: "Top",
      farmingTags: ["Best easy farm", "Dense spawn"],
      farmingReason: "Top-tier density and route speed."
    },
    {
      id: "zakum",
      name: "Zakum",
      image: null,
      portrait: "ZA",
      type: "Boss",
      category: "Demon",
      level: 110,
      hp: 660000000,
      strength: 92,
      difficulty: 88,
      difficultyLabel: "Extreme",
      description: "The classic arm-phase boss that defines clean pattern handling.",
      shortDescription: "Classic arm-phase boss.",
      weaknesses: ["Holy Weak", "Pattern punishable after arm break"],
      drops: [{ name: "Zakum Helmet", rarity: "Epic", kind: "Equipment" }],
      locations: [{ region: "El Nath", map: "Altar of Zakum", area: "Boss arena" }],
      isBoss: true,
      isElite: false,
      farmingScore: 28,
      farmingTier: "Low",
      farmingTags: ["Boss route"],
      farmingReason: "Great progression value, not a farming target."
    }
  ],
  meta: {
    sourceName: "StrategyWiki MapleStory",
    sourceUrl: "https://strategywiki.org/wiki/MapleStory/Monsters",
    copyrightLabel: "Source: StrategyWiki MapleStory / curated preview",
    updatedAt: "2026-04-10T12:00:00.000Z",
    syncState: "seeded",
    itemCount: 4
  }
};
