/**
 * idlestoryItemDatabase.ts
 *
 * Bundle-friendly item database curated from public/items-feed.json.
 * Generated by scripts/build-idlestory-item-db.mjs.
 *
 * Use this as the default fallback database when resolving IdleStory item
 * visuals. The runtime UI may pass a larger or more authoritative database
 * (e.g. via the items prop) and that one wins; if a match is not found
 * there, the resolver falls back to this bundle so every item still gets
 * a real image.
 */

import bundle from './idlestoryItemDatabase.json';
import type { ItemDatabaseEntry } from '../components/content/minigames/idlestory/itemVisuals';

type RawBundleItem = {
  id: string;
  name: string;
  image: string;
  type: string;
  category: string;
  rarity: string;
  level?: number | null;
  idleType?: string;
};

type RawBundle = {
  meta: {
    generatedAt: string;
    sourceCount: number;
    bundledCount: number;
    perBucketCap: number;
    bucketSizes: Record<string, number>;
  };
  items: RawBundleItem[];
};

const raw = bundle as RawBundle;

/** Curated entries cast to the resolver-friendly shape. */
export const idlestoryItemDatabase: readonly ItemDatabaseEntry[] = raw.items.map(
  (item): ItemDatabaseEntry => ({
    id: item.id,
    name: item.name,
    image: item.image,
    type: item.type,
    category: item.category,
    rarity: item.rarity,
    level: item.level ?? null,
    idleType: item.idleType as ItemDatabaseEntry['idleType']
  })
);

export const idlestoryItemDatabaseMeta = raw.meta;

/** Convenience helper: only entries whose idleType matches the requested type. */
export function getDatabaseEntriesForType(type: string): ItemDatabaseEntry[] {
  return idlestoryItemDatabase.filter((entry) => entry.idleType === type);
}
